##############################################################
# build on schedule or trigger 
# check kernel versions and trigger to generate last tagged version

check-master-schedule:
    image: $CI_REGISTRY/docker/bob-the-builder/buster:latest
    tags: ['amd64']
    only:
        - triggers
        - schedules
    before_script: 
        - apt-get update
        - apt-get install -y axon-kernel-headers
    script:
        - bash kernels_check.sh

