variables:
#    TEMPLATE_DISABLE: "1"
    TEMPLATE_DEB_NAME: "unipi-kernel-modules"

include: 
    project: docker/template
    file: debian-pkg.yaml


#######################################################################################
######### Modified from debian-pkg.yaml - REMOVE in final branch ######################
#######################################################################################

.g1build_for_stable:
    stage: build_package
    image: $CI_REGISTRY/docker/bob-the-builder/$STABLE_CODENAME:latest
    only: ['g1']
    variables:
        VERSION_SUFFIX: ""
        GIT_STRATEGY: clone
        GIT_CHECKOUT: "true"
    script:
        - /ci-scripts/build-package.sh $TEMPLATE_DEB_NAME
    artifacts:
        paths:
            - build/
            - debian/changelog

#######################################################################################
######### END END                         REMOVE in final branch ######################
#######################################################################################

##############################################################
## set empty VERSION_SUFFIX; package names are concatenated with 
##      last kernel name, so they differs for distributions

build-stable:g1:
    extends: .g1build_for_stable
    tags: ['arm64']
    variables:
        PLATFORM: "g1"
    only: 
        variables: [$DISABLE_STABLE_ARM64==null, $DISABLE_STABLE_ARM64=="0"]
    before_script: 
        - apt-get update
        - apt-get install -y g1-kernel-headers

.build-stable:nano:
    extends: .g1build_for_stable
    tags: ['arm64']
    variables:
        PLATFORM: "axon"
    only: 
        variables: [$DISABLE_STABLE_ARM64==null, $DISABLE_STABLE_ARM64=="0"]
    before_script: 
        - apt-get update
        - apt-get install -y axon-kernel-headers


deploy-test:
    extends: .deploy_test

