# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_MXC) += unipi-zulu.dtb \
			  unipi-zulu-gpiotest.dtb \
			  unipi-zulu-altboot.dtb \

dtb-$(CONFIG_ARCH_ROCKCHIP) += unipi-g1.dtb

DTC_FLAGS := -@
